### ISSUE TITLE
How can I open existing ThingML files in Eclipse

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#46]
During training 1.  we were learned to do the new project wizard ....
This wizard makes a complete project for traingin 1.

Now I want to make my own project ... but I dont know how.
I can run the wizard and then replace the project files....

**Comment by brice-morin** [comment]
I agree this is not perfect, but that is the way to do it for now. I will integrate the tutorial #3 in the default files, so that it is there too. Later we'll make a proper New project feature that simply deploy the minimal set of thingml files to get started with you own projects, without the overhead of all the tutorial files

**Comment by brice-morin** [comment]
Or you can create any sort of project in Eclipse and then you should be able to create .thingml files

**Comment by sdalgard** [comment]
Ok, I can live with that for now...
