### ISSUE TITLE
How to combine Generated Java(ThingML) and Java(manual) in Kevoree

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#51]
In training 3. I want to have several components in my javanode.
 - One component is generated Java from ThingML
 - Another comonents are manually written Java

I dont want to not have the manually written Java into the directories with generated Java.
This may lead to overwritten files...

How do I set up this so Kevoree find all the components referred in the Kev-script?

**Comment by brice-morin** [comment]
I guess you have to:
- create a separate Java project containing the APIs, and move the `org.thingml.generated.api` package into it (generated by ThingML)
- one Kevoree project with your manually written Java/Kevoree code
- one project for the generated ThingML code

If you `mvn clean install` into all these projects, every project should then be aware of the others.

Then you should use the API project to link the two other projects.

**Comment by sdalgard** [comment]
@maxleiko 
I dont see how that directory structure will look like.
Will there then be two pom files?
Previous turorial I tried with two projects and a root pom file in addition to the two project pom files.
   This approach failed because the jar didnt contain all kev-stuff.
Maxime showed me how to combine it into one package.
   Now it will be several packages(?)

**Comment by brice-morin** [comment]
Maybe three independent `POM.xml` files:
- one fairly basic for the API project
- one with all kev-stuff + a dependency to the API
- one with all thingml-stuff + kev-stuff (generated) + a dependency to the API

In the end you will deploy two distincts (sets of) Kevoree components, the one(s) you wrote manually and the one(s) generated from ThingML. I do not think it should be a problem.... but @maxleiko knows best ;-)

**Comment by maxleiko** [comment]
Currently, while you are in dev-mode in Kevoree Java, you cannot run a KevScript that uses two separate Kevoree project because it won't "load" the generated Kevoree model of the "other" module.  
So you will have to manually add the source code in one and only one project.  

We could do a fix for that, just like I made for Kevoree JS though.

**Comment by maxleiko** [comment]
This is due to the fact that the KevScript interpreter tries to check on the registry while it cannot find DeployUnit. And the DeployUnits created by your other projects are not published on the registry.
To bypass that, the Kevoree plugin loads your current model before interpretation so the check to the registry is not necessary.

**Comment by brice-morin** [comment]
Yes, it was a useful fix in Kevoree JS. That would be nice to have the same feature in Kevoree Java. Otherwise it will rapidly become cumbersome to develop HD-services with Kevoree where we have to develop everthing in a centralized way in one single project.......

**Comment by maxleiko** [comment]
Agreed. I will dig into that.

**Comment by maxleiko** [comment]
Alright, so I'm deploying **Kevoree 5.2.6-SNAPSHOT** that contains the fix for local multi-projects development workflow.  
This fix allows you to specify, in the Maven Kevoree Plugin, a list of **local libraries** to merge.

```xml
<!-- Kevoree plugin -->
<plugin>
  <groupId>org.kevoree.tools</groupId>
  <artifactId>org.kevoree.tools.mavenplugin</artifactId>
  <version>5.2.6-SNAPSHOT</version>
    <configuration>
        <mergeLocalLibraries>
            <mergeLocalLibrary>/tmp/MyOtherComp/target/classes</mergeLocalLibrary>
        </mergeLocalLibraries>
    </configuration>
</plugin>
```

But you can also specify those paths as a command-line argument:

```sh
mvn kev:run -Ddev.target.dirs=/tmp/MyOtherComp/target/classes:/tmp/AnotherOne/target/classes
```

If you manage to use it sucessfully, I'll release a 5.2.6 version of Kevoree. But I'll wait for your feedback first :)

**Comment by brice-morin** [comment]
@sdalgard do you have time these days to try that new feature?

**Comment by maxleiko** [comment]
You will have to add those line to the pom.xml in order to get access to SNAPSHOT builds

```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </pluginRepository>
</pluginRepositories>
```

**Comment by brice-morin** [comment]
Re-assigned to Steffen just to test the new feature.

**Comment by sdalgard** [comment]
It is woking and used in my checked in contribution:

https://github.com/sdalgard/training/blob/master/3.Wrapping_ThingML_into_Kevoree/3.3_Contrib/SINTEF-INST/3.3-contrib/trunkmux/pom.xml

**Comment by brice-morin** [comment]
@maxleiko can you release 5.2.6? (Maybe test it in depth to make sure something else is broken)
