### ISSUE TITLE
How to replace the WsMsgBroker by some other broker?

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#67]
This is related to https://github.com/HEADS-project/training/tree/master/2.Kevoree_Basics/6.Contrib/SAG and #53.
What are the technical requirements for a broker / message bus to replace WsMsgBroker?
What protocols are used by WsMsgBroker? 

Looks like WsMsgBroker is sending the same message several times on one channel.

**Comment by maxleiko** [comment]
There is no requirements to replace WsMsgBroker, you are free to use anything you want.  
**WsMsgBroker** is just a WebSocket server/broker that I have made because I could not find anything else using only WebSockets and providing a "basic but handy" protocol. But it is clearly not perfect.  

You can find some documentation about its protocol [there](https://github.com/maxleiko/wsmsgbroker)

**Comment by maxleiko** [comment]
@skorsky can you close this is the answer suits you?

**Comment by skorsky** [comment]
@maxleiko - I'm just working on this.

**Comment by skorsky** [comment]
I connected the JavaNode with our messaging product, which supports WebSockets, but the communication breaks. With a monitor I got this on the wire. No clue what the binary stuff is.

@maxleiko any idea?

==== Request ====
GET / HTTP/1.1
Origin: localhost
Sec-WebSocket-Key: hSNm+p1zAtMfKDiom7Y0gw==
Connection: upgrade
Sec-WebSocket-Version: 13
Upgrade: websocket
Host: 127.0.0.1:9050

?ÖÐŸpº«½Ù¤öÔò¥RÈµøÉ¤ú˜ü½Þò¥R•¾ðß£ÄÕ´ú@çÿü× ðß¾ëá½æ3Õ½ï-•¢úÏ¹íÞ‹ðÎ?êÏµÂ/Ù¸þŠòâˆ€8Žþ<
==== Response ====
HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: e27ORht+IeUvXHh6GbnSVnHkUBA=

?[{"d":[3,""]}]
==============

**Comment by maxleiko** [comment]
No idea. It's pretty weird.

**Comment by skorsky** [comment]
OK, I'll leave this as is for now.
